"""!
@file gen_coastline.py
@brief Generate orbital_sentinel/coastline.h from the desktop coastline.json.
@details
    The desktop app stores the decimated Natural Earth 110m coastline as a list of
    (lon, lat) polylines. The firmware does not carry a JSON parser or floats it
    does not need, so we bake the dots into a flat const table of int16 pairs in
    hundredths of a degree:

        lon in [-180.00, 180.00] -> [-18000, 18000]   (fits int16)
        lat in  [-90.00,  90.00] -> [ -9000,  9000]

    Two int16 per dot = 4 bytes. With STRIDE=2 (matching SmallRenderer's default
    coast_stride) that is ~2.6k dots, ~10 KB of flash - trivial on a 4 MB ESP32-S3
    but far too much to hold as text.

    Usage:
        python tools/gen_coastline.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(
    HERE, "..", "..", "orca_orbital_sentinel", "data", "coastline.json"))
DST = os.path.normpath(os.path.join(
    HERE, "..", "orbital_sentinel", "coastline.h"))

# Keep every Nth dot. 2 mirrors render_small.SmallRenderer(coast_stride=2), which
# is what the desktop small-screen mode already uses for a 240x240 panel.
STRIDE = 2


def main():
    with open(SRC, "r", encoding="utf-8") as handle:
        polylines = json.load(handle)

    dots = []
    for line in polylines:
        for lon, lat in line:
            dots.append((lon, lat))
    dots = dots[::STRIDE]

    rows = []
    for lon, lat in dots:
        lon_i = max(-18000, min(18000, int(round(lon * 100.0))))
        lat_i = max(-9000, min(9000, int(round(lat * 100.0))))
        rows.append("  {{{0:6d},{1:6d}}},".format(lon_i, lat_i))

    body = "\n".join(rows)
    header = """/**
 * @file coastline.h
 * @brief Natural Earth 110m coastline dots, baked as int16 centidegrees.
 * @details
 *     GENERATED by tools/gen_coastline.py from
 *     orca_orbital_sentinel/data/coastline.json - do not edit by hand.
 *
 *     Layout: {{lon, lat}} pairs in hundredths of a degree. The firmware lifts
 *     each pair onto the unit sphere once at boot (see coastToEcef in render.cpp)
 *     and reuses the resulting ECEF cloud every frame.
 *
 *     Source data is public domain (Natural Earth).
 *
 *     Dots: {count}   Stride: {stride}   Flash: ~{bytes} bytes
 */

#ifndef ORBITAL_SENTINEL_COASTLINE_H
#define ORBITAL_SENTINEL_COASTLINE_H

#include <stdint.h>

#define COAST_DOT_COUNT {count}

/// {{lon, lat}} in centidegrees; divide by 100.0f for degrees.
static const int16_t COAST_DOTS[COAST_DOT_COUNT][2] = {{
{body}
}};

#endif  // ORBITAL_SENTINEL_COASTLINE_H
""".format(count=len(dots), stride=STRIDE, bytes=len(dots) * 4, body=body)

    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as handle:
        handle.write(header)

    print("wrote {0}".format(DST))
    print("  {0} dots (stride {1}), ~{2} bytes of flash".format(
        len(dots), STRIDE, len(dots) * 4))


if __name__ == "__main__":
    main()
